<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Include="extension.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
    <None Include="assets/**/*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseLocalCoveSdk)' == 'false'">
    <PackageReference Include="Cove.Sdk" Version="$(CoveSdkVersion)" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseLocalCoveSdk)' == 'true' and Exists('$(LocalCoveSdkPath)')">
    <ProjectReference Include="$(LocalCoveSdkPath)">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>
</Project>
